"""empty message

Revision ID: d3d70db437a1
Revises: 
Create Date: 2025-03-15 17:56:23.372134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d70db437a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('ingredients', sa.TEXT(), nullable=False),
    sa.Column('cooking_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('stars_rating', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
